const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const state = { user:null, workspaces:[], workspaceId:null, sourceMode:'upload', source:null, current:null, projects:[], analytics:null };

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2600)}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(v){return new Intl.NumberFormat('pt-BR',{notation:Number(v)>=10000?'compact':'standard',maximumFractionDigits:1}).format(Number(v||0))}
function pct(v){return `${(Number(v||0)*100).toFixed(1)}%`}
function setBusy(btn,on,busy,normal){btn.disabled=on;btn.textContent=on?busy:normal}
function workspaceHeaders(){return state.workspaceId?{'X-Workspace-Id':state.workspaceId}:{}}
async function api(url,opt={}){const headers={...workspaceHeaders(),...(opt.headers||{})};if(opt.body && !(opt.body instanceof Blob) && !(opt.body instanceof ArrayBuffer) && !headers['Content-Type'])headers['Content-Type']='application/json';const r=await fetch(url,{...opt,headers});let data=null;try{data=await r.json()}catch{}if(r.status===401){showAuth();throw new Error(data?.error||'Faça login')}if(!r.ok)throw new Error(data?.error||`Erro ${r.status}`);return data}
function showAuth(){$('#authScreen').classList.remove('hidden');$('#app').classList.add('hidden')}
function showApp(){$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden')}
function currentWorkspace(){return state.workspaces.find(w=>w.id===state.workspaceId)||state.workspaces[0]}

async function loadMe(){try{const d=await api('/api/me');state.user=d.user;state.workspaces=d.workspaces||[];state.workspaceId=state.workspaceId||state.workspaces[0]?.id||null;showApp();renderIdentity();await onWorkspaceChange()}catch{showAuth()}}
function renderIdentity(){if(!state.user)return;$('#userName').textContent=state.user.name;$('#userEmail').textContent=state.user.email;$('#workspaceSelect').innerHTML=state.workspaces.map(w=>`<option value="${w.id}" ${w.id===state.workspaceId?'selected':''}>${escapeHtml(w.name)}</option>`).join('');const ws=currentWorkspace();$('#workspacePill').textContent=ws?.name||'—'}
async function onWorkspaceChange(){renderIdentity();state.current=null;state.source=null;resetSource();await Promise.all([loadStatus(),loadProjects(),loadCalendar(),loadAnalytics(),loadInstagramSettings()])}
async function loadStatus(){try{const [s,w]=await Promise.all([api('/api/status'),api('/api/workspace-status')]);const ok=s.aiConfigured&&s.ffmpegAvailable;$('#connectionDot').className=`dot ${ok?'good':'bad'}`;$('#connectionTitle').textContent=ok?'Pronto para recortar':'Configuração pendente';$('#connectionText').textContent=`IA ${s.aiConfigured?'✓':'×'} • FFmpeg ${s.ffmpegAvailable?'✓':'×'} • Instagram ${w.instagramConfigured?'✓':'○'}`;$('#statusAi').textContent=s.aiConfigured?'IA pronta':'IA pendente';$('#statusFfmpeg').textContent=s.ffmpegAvailable?'FFmpeg pronto':'FFmpeg pendente';if(!s.youtubeImportEnabled)$('#sourceYoutubePane .micro').textContent='O campo está pronto, mas o servidor precisa habilitar a importação por link. Upload já funciona normalmente.'}catch(e){toast(e.message)}}

function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===name));const titles={studio:'Recortador inteligente',projects:'Meus clipes',calendar:'Calendário de publicação',analytics:'Analytics + aprendizado',settings:'Integrações'};$('#viewTitle').textContent=titles[name]||'ViraClip AI'}

function resetSource(){state.source=null;$('#videoFile').value='';$('#youtubeUrl').value='';$('#rightsConfirmed').checked=false;$('#fileRow').classList.add('hidden');$('#resultsSection').classList.add('hidden');$('#progressPanel').classList.add('hidden');$('#clipGrid').innerHTML='';selectClip(null)}
function fileSize(bytes){const u=['B','KB','MB','GB'];let n=Number(bytes||0),i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`}
function sourceFileChanged(){const f=$('#videoFile').files?.[0];if(!f)return;$('#fileName').textContent=f.name;$('#fileMeta').textContent=`${fileSize(f.size)} • ${f.type||'vídeo'}`;$('#fileRow').classList.remove('hidden')}
function progress(percent,title,text,done=0){$('#progressPanel').classList.remove('hidden');$('#progressPct').textContent=`${Math.round(percent)}%`;$('#progressBar').style.width=`${percent}%`;$('#progressTitle').textContent=title;$('#progressText').textContent=text;['#pUpload','#pTranscribe','#pSelect','#pRender'].forEach((id,i)=>$(id).classList.toggle('done',i<done))}
async function uploadSource(file){progress(8,'Enviando o vídeo…','O arquivo está sendo enviado ao ViraClip.',0);const r=await fetch('/api/source-upload',{method:'POST',headers:{...workspaceHeaders(),'Content-Type':file.type||'application/octet-stream','X-File-Name':encodeURIComponent(file.name)},body:file});let d;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error||`Falha no upload (${r.status})`);progress(24,'Upload concluído','Agora vamos transcrever o áudio e entender o vídeo.',1);return d}
async function importYoutube(){const url=$('#youtubeUrl').value.trim();if(!url)throw new Error('Cole o link do vídeo do YouTube');if(!$('#rightsConfirmed').checked)throw new Error('Confirme que você tem autorização para reutilizar o vídeo');progress(8,'Importando do YouTube…','Preparando o vídeo autorizado para análise.',0);const d=await api('/api/import-youtube',{method:'POST',body:JSON.stringify({url,rightsConfirmed:true})});progress(24,'Importação concluída','Agora vamos transcrever e encontrar os melhores trechos.',1);return {...d,sourceUrl:url}}
async function processVideo(){const btn=$('#processBtn');setBusy(btn,true,'Processando…','✦ Criar clipes automaticamente');try{let src;if(state.sourceMode==='upload'){const f=$('#videoFile').files?.[0];if(!f)throw new Error('Escolha um vídeo primeiro');src=await uploadSource(f);src.sourceTitle=f.name}else src=await importYoutube();state.source=src;let fake=26;const timer=setInterval(()=>{fake=Math.min(82,fake+Math.random()*4);const stage=fake<52?['Transcrevendo o vídeo…','A IA está convertendo a fala em texto com timestamps.',1]:fake<68?['Encontrando os melhores momentos…','Analisando ganchos, histórias, frases fortes e trechos completos.',2]:['Renderizando os clipes…','Convertendo para 9:16 e queimando as legendas no vídeo.',3];progress(fake,stage[0],stage[1],stage[2])},1400);let d;try{d=await api('/api/clip-source',{method:'POST',body:JSON.stringify({sourceId:src.sourceId,sourceTitle:src.sourceTitle||'',sourceUrl:src.sourceUrl||'',count:Number($('#clipCount').value),minDuration:Number($('#minDuration').value),maxDuration:Number($('#maxDuration').value),goal:$('#clipGoal').value})})}finally{clearInterval(timer)}progress(100,'Clipes prontos!','Selecione um corte para baixar, publicar ou agendar.',4);renderClipResults(d.items||[]);await loadProjects();toast(`${d.items?.length||0} clipes criados ✓`)}catch(e){toast(e.message);progress(0,'Não foi possível processar',e.message,0)}finally{setBusy(btn,false,'Processando…','✦ Criar clipes automaticamente')}}
function clipMeta(p){const src=p.scenes?.[0]?.source||{};return {score:Number(p.viralScore??src.viralScore??0),reason:p.reason||src.reason||'',start:Number(p.clipStart??src.start??0),end:Number(p.clipEnd??src.end??p.duration??0)}}
function clipCard(p){const m=clipMeta(p);const score=m.score?`<span class="score">${Math.round(m.score)}/100</span>`:'';return `<article class="clip-card"><div class="clip-video">${p.videoUrl?`<video src="${escapeHtml(p.videoUrl)}" controls playsinline preload="metadata"></video>`:'<span class="muted">Sem vídeo</span>'}</div><div class="clip-body"><div class="clip-top"><h3>${escapeHtml(p.idea||p.hook||'Corte')}</h3>${score}</div><div class="clip-meta">${Math.round(p.duration||m.end-m.start)}s ${m.start?`• ${Math.floor(m.start/60)}:${String(Math.floor(m.start%60)).padStart(2,'0')}`:''}</div><p>${escapeHtml(m.reason||p.hook||'')}</p><div class="clip-actions"><button class="primary" data-select-clip="${p.id}">Usar este</button>${p.videoUrl?`<a class="secondary" href="${escapeHtml(p.videoUrl)}" download>Baixar</a>`:''}</div></div></article>`}
function bindClipButtons(root){root.querySelectorAll('[data-select-clip]').forEach(b=>b.onclick=()=>{const p=[...state.projects,...(state.lastResults||[])].find(x=>x.id===b.dataset.selectClip);selectClip(p);toast('Clipe selecionado')})}
function renderClipResults(items){state.lastResults=items;$('#resultsSection').classList.remove('hidden');$('#resultsTitle').textContent=`${items.length} clipes encontrados`;const grid=$('#clipGrid');grid.innerHTML=items.map(clipCard).join('');bindClipButtons(grid);setTimeout(()=>$('#resultsSection').scrollIntoView({behavior:'smooth',block:'start'}),100)}
function selectClip(p){state.current=p||null;$('#currentVideo').textContent=p?`${p.idea||p.hook||'Clipe'} • ${p.duration||0}s`:'Nenhum clipe selecionado.';$('#publishCaption').value=p?.caption||''}

async function loadProjects(){try{const d=await api('/api/projects');state.projects=(d.items||[]).filter(p=>p.niche==='Recorte IA'||p.videoUrl);const grid=$('#projectGrid');grid.innerHTML=state.projects.length?state.projects.map(clipCard).join(''):'<p class="muted">Nenhum clipe ainda. Envie seu primeiro vídeo.</p>';bindClipButtons(grid)}catch{}}
async function publish(){if(!state.current)return toast('Selecione um clipe');const btn=$('#publishBtn');setBusy(btn,true,'Publicando…','↗ Publicar agora');try{await api('/api/publish-instagram',{method:'POST',body:JSON.stringify({projectId:state.current.id,caption:$('#publishCaption').value,shareToFeed:$('#shareToFeed').checked})});toast('Reel publicado ✓');await Promise.all([loadProjects(),loadAnalytics()])}catch(e){toast(e.message)}finally{setBusy(btn,false,'Publicando…','↗ Publicar agora')}}
async function schedule(){if(!state.current)return toast('Selecione um clipe');const val=$('#publishAt').value;if(!val)return toast('Escolha data e hora');try{await api('/api/schedules',{method:'POST',body:JSON.stringify({projectId:state.current.id,caption:$('#publishCaption').value,shareToFeed:$('#shareToFeed').checked,publishAt:new Date(val).toISOString()})});toast('Publicação agendada ✓');await loadCalendar()}catch(e){toast(e.message)}}

async function loadCalendar(){try{const data=await api('/api/calendar');const schedules=data.schedules||[];const days=[];for(let i=0;i<14;i++){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+i);days.push(d)}$('#calendarGrid').innerHTML=days.map(d=>{const ev=schedules.filter(x=>new Date(x.publish_at).toDateString()===d.toDateString());return `<div class="calendar-day ${d.toDateString()===new Date().toDateString()?'today':''}"><div class="date">${d.toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'})}</div>${ev.map(e=>`<div class="cal-event">${escapeHtml((e.caption||'Reel').slice(0,45))}<br><small>${new Date(e.publish_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')}</div>`}).join('');const q=await api('/api/schedules');$('#scheduleGrid').innerHTML=(q.items||[]).length?(q.items||[]).slice(0,20).map(s=>`<article class="schedule-card"><h3>${new Date(s.publishAt).toLocaleString('pt-BR')}</h3><p>${escapeHtml((s.caption||'Reel').slice(0,90))}</p><span class="status">${s.status}</span></article>`).join(''):'<p class="muted">Fila vazia.</p>'}catch{}}
async function loadAnalytics(){try{state.analytics=await api('/api/analytics');renderAnalytics()}catch{}}
function renderAnalytics(){const d=state.analytics||{summary:{},items:[]};$('#kpiViews').textContent=fmt(d.summary.views);$('#kpiReach').textContent=fmt(d.summary.reach);$('#kpiInteractions').textContent=fmt(d.summary.interactions);$('#kpiEngagement').textContent=pct(d.summary.engagementRate);const rows=(d.items||[]).filter(x=>x.metrics?.capturedAt).sort((a,b)=>b.metrics.engagementRate-a.metrics.engagementRate);$('#analyticsTable').innerHTML=`<div class="analytics-row header"><span>Clipe</span><span>Views</span><span>Alcance</span><span>Interação</span><span>Retenção</span></div>`+rows.slice(0,20).map(x=>`<div class="analytics-row"><b>${escapeHtml((x.idea||x.hook||'Clipe').slice(0,55))}</b><span>${fmt(x.metrics.views)}</span><span>${fmt(x.metrics.reach)}</span><span>${pct(x.metrics.engagementRate)}</span><span>${pct(x.metrics.retentionProxy)}</span></div>`).join('');const s=d.strategy||{summary:'Ainda não há dados suficientes.',recommendations:[]};const html=`<b>${escapeHtml(s.summary||'')}</b>${s.recommendations?.length?`<ul>${s.recommendations.map(r=>`<li>${escapeHtml(r)}</li>`).join('')}</ul>`:'<p>Publique clipes e atualize os analytics.</p>'}`;$('#analyticsStrategy').innerHTML=html;$('#strategyCard').innerHTML=html}
async function refreshAnalytics(){const btn=$('#refreshAnalyticsBtn');setBusy(btn,true,'Atualizando…','Atualizar Instagram');try{const d=await api('/api/analytics/refresh',{method:'POST',body:'{}'});state.analytics=d.dashboard;state.analytics.strategy=d.strategy;renderAnalytics();toast('Analytics atualizados ✓')}catch(e){toast(e.message)}finally{setBusy(btn,false,'Atualizando…','Atualizar Instagram')}}
async function demoAnalytics(){try{const d=await api('/api/analytics/demo',{method:'POST',body:'{}'});state.analytics=d.dashboard;state.analytics.strategy=d.strategy;renderAnalytics();toast('Dados demo gerados')}catch(e){toast(e.message)}}
async function rebuildStrategy(){try{const s=await api('/api/strategy/rebuild',{method:'POST',body:'{}'});if(!state.analytics)await loadAnalytics();else{state.analytics.strategy=s;renderAnalytics()}toast('Estratégia recalculada')}catch(e){toast(e.message)}}

async function loadInstagramSettings(){try{const d=await api('/api/integrations/instagram');$('#igAccountId').value=d.accountId||'';$('#igGraphVersion').value=d.graphVersion||'v24.0';$('#publicBaseUrl').value=d.publicBaseUrl||'';$('#igToken').value='';$('#igIntegrationState').textContent=d.hasToken?'Token configurado. Deixe o campo vazio para manter o atual.':'Instagram ainda não configurado.'}catch{}}
async function saveInstagram(){const btn=$('#saveInstagramBtn');setBusy(btn,true,'Salvando…','Salvar integração');try{await api('/api/integrations/instagram',{method:'PUT',body:JSON.stringify({accountId:$('#igAccountId').value,accessToken:$('#igToken').value,graphVersion:$('#igGraphVersion').value,publicBaseUrl:$('#publicBaseUrl').value})});$('#igToken').value='';await Promise.all([loadInstagramSettings(),loadStatus()]);toast('Integração salva ✓')}catch(e){toast(e.message)}finally{setBusy(btn,false,'Salvando…','Salvar integração')}}
async function createWorkspace(){const name=$('#newWorkspaceName').value.trim();if(!name)return toast('Digite o nome do perfil');try{const w=await api('/api/workspaces',{method:'POST',body:JSON.stringify({name})});state.workspaces.push(w);state.workspaceId=w.id;$('#newWorkspaceName').value='';await onWorkspaceChange();toast('Perfil criado ✓')}catch(e){toast(e.message)}}

$$('[data-auth-tab]').forEach(b=>b.onclick=()=>{$$('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').classList.toggle('hidden',b.dataset.authTab!=='login');$('#registerForm').classList.toggle('hidden',b.dataset.authTab!=='register');$('#authError').textContent=''});
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#loginEmail').value,password:$('#loginPassword').value})});await loadMe()}catch(err){$('#authError').textContent=err.message}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('#registerName').value,email:$('#registerEmail').value,password:$('#registerPassword').value,workspaceName:$('#registerWorkspace').value})});await loadMe()}catch(err){$('#authError').textContent=err.message}};
$('#logoutBtn').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST',body:'{}'})}catch{}showAuth()};
$('#workspaceSelect').onchange=async e=>{state.workspaceId=e.target.value;await onWorkspaceChange()};
$('#addWorkspaceBtn').onclick=()=>switchView('settings');
$$('.nav').forEach(n=>n.onclick=()=>switchView(n.dataset.view));
$$('[data-source-tab]').forEach(b=>b.onclick=()=>{state.sourceMode=b.dataset.sourceTab;$$('[data-source-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#sourceUploadPane').classList.toggle('hidden',state.sourceMode!=='upload');$('#sourceYoutubePane').classList.toggle('hidden',state.sourceMode!=='youtube')});
$('#videoFile').onchange=sourceFileChanged;$('#clearFileBtn').onclick=()=>{$('#videoFile').value='';$('#fileRow').classList.add('hidden')};
$('#processBtn').onclick=processVideo;$('#publishBtn').onclick=publish;$('#scheduleBtn').onclick=schedule;$('#refreshProjectsBtn').onclick=loadProjects;$('#refreshProjectsBtnInline').onclick=loadProjects;$('#refreshCalendarBtn').onclick=loadCalendar;$('#refreshAnalyticsBtn').onclick=refreshAnalytics;$('#demoAnalyticsBtn').onclick=demoAnalytics;$('#rebuildStrategyBtn').onclick=rebuildStrategy;$('#saveInstagramBtn').onclick=saveInstagram;$('#createWorkspaceBtn').onclick=createWorkspace;$('#newProjectBtn').onclick=()=>{resetSource();switchView('studio')};
loadMe();
