'use strict';

const fs=require('fs');
const path=require('path');
const os=require('os');
const crypto=require('crypto');
const {DatabaseSync}=require('node:sqlite');

const DATA_DIR=process.env.DATA_DIR||path.join(process.cwd(),'data');
const JOB_DIR=process.env.JOB_DIR||path.join(DATA_DIR,'jobs');
const DB_PATH=process.env.DATABASE_PATH||path.join(DATA_DIR,'viraclip-v7.sqlite');
const CLOUD=process.env.CLOUDINARY_CLOUD_NAME||'';
const CLOUD_KEY=process.env.CLOUDINARY_API_KEY||'';
const CLOUD_SECRET=process.env.CLOUDINARY_API_SECRET||'';
const GROQ_KEY=process.env.GROQ_API_KEY||'';
const TEXT_MODEL=process.env.GROQ_TEXT_MODEL||'openai/gpt-oss-20b';
const TRANSCRIBE_MODEL=process.env.GROQ_TRANSCRIBE_MODEL||'whisper-large-v3-turbo';
const jobId=process.argv[2];
if(!jobId)throw new Error('jobId ausente');
const jobPath=path.join(JOB_DIR,`${jobId}.json`),inputPath=path.join(JOB_DIR,`${jobId}.input.json`);
const input=JSON.parse(fs.readFileSync(inputPath,'utf8'));
const db=new DatabaseSync(DB_PATH);
const now=()=>new Date().toISOString();
const uid=p=>`${p}_${crypto.randomBytes(10).toString('hex')}`;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
const clean=(v,n=4000)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,n);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function writeJob(p){let j={};try{j=JSON.parse(fs.readFileSync(jobPath,'utf8'))}catch{};const next={...j,...p,updatedAt:now()};const tmp=`${jobPath}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify(next));fs.renameSync(tmp,jobPath)}
function encodePublicId(id){return String(id||'').split('/').map(encodeURIComponent).join('/')}
function lineScore(text){const t=String(text||'').toLowerCase();let s=Math.min(3,t.length/180);if(/[?!]/.test(t))s+=2;if(/\b\d+[\d.,%]*\b/.test(t))s+=1;if(/\b(você|como|porque|segredo|erro|nunca|sempre|melhor|pior|verdade|descobri|aprendi|atenção|importante|problema|resultado|dinheiro|incrível|absurdo|olha|imagina|mas|então)\b/i.test(t))s+=2;return s}
function srtTime(sec){const ms=Math.max(0,Math.round(sec*1000)),h=String(Math.floor(ms/3600000)).padStart(2,'0'),m=String(Math.floor(ms%3600000/60000)).padStart(2,'0'),s=String(Math.floor(ms%60000/1000)).padStart(2,'0'),x=String(ms%1000).padStart(3,'0');return `${h}:${m}:${s},${x}`}
function makeSrt(segments,start,end,fallback){const rows=[];for(const seg of segments){const a=Math.max(start,Number(seg.start||0)),b=Math.min(end,Number(seg.end||0));if(b-a<.08)continue;const text=String(seg.text||'').trim();if(!text)continue;rows.push(`${rows.length+1}\n${srtTime(a-start)} --> ${srtTime(b-start)}\n${text}\n`)}if(!rows.length)rows.push(`1\n00:00:00,000 --> ${srtTime(Math.max(.5,end-start))}\n${fallback||'Trecho selecionado'}\n`);return rows.join('\n')}
async function fetchWithRetry(url,options={},attempts=6){let last;for(let i=1;i<=attempts;i++){try{const r=await fetch(url,options);if(r.ok)return r;if(![408,423,425,429,500,502,503,504].includes(r.status))return r;last=new Error(`HTTP ${r.status}`)}catch(e){last=e}if(i<attempts)await sleep(Math.min(15000,1200*Math.pow(1.8,i-1)))}throw last||new Error('Falha de rede')}
function audioUrl(publicId){return `https://res.cloudinary.com/${encodeURIComponent(CLOUD)}/video/upload/ac_mp3,af_16000,br_48k,fl_mono/${encodePublicId(publicId)}.mp3`}
async function transcribe(publicId){writeJob({stage:'transcribing',percent:31,message:'Preparando áudio na nuvem'});const r=await fetchWithRetry(audioUrl(publicId));if(!r.ok)throw new Error(`Cloudinary não conseguiu preparar o áudio (${r.status})`);const buf=Buffer.from(await r.arrayBuffer());writeJob({stage:'transcribing',percent:42,message:'Transcrevendo o áudio com Groq'});const form=new FormData();form.append('file',new Blob([buf],{type:'audio/mpeg'}),'audio.mp3');form.append('model',TRANSCRIBE_MODEL);form.append('language','pt');form.append('response_format','verbose_json');form.append('timestamp_granularities[]','segment');const gr=await fetchWithRetry('https://api.groq.com/openai/v1/audio/transcriptions',{method:'POST',headers:{Authorization:`Bearer ${GROQ_KEY}`},body:form},4);const j=await gr.json();if(!gr.ok)throw new Error(j?.error?.message||`Groq ${gr.status}`);const segments=(j.segments||[]).map(s=>({start:Number(s.start||0),end:Number(s.end||0),text:String(s.text||'').trim()}));return {segments,text:segments.map(s=>s.text).join(' ')}}
function fallbackCuts(duration,count,minD,maxD,segments){const d=Math.min(maxD,Math.max(minD,35)),cand=segments.map(s=>({start:s.start,text:s.text,score:lineScore(s.text)})).sort((a,b)=>b.score-a.score),out=[];for(const c of cand){if(out.length>=count)break;const start=clamp(c.start-2,0,Math.max(0,duration-d));if(out.some(x=>Math.abs(x.start-start)<d*.65))continue;out.push({start,end:Math.min(duration,start+d),title:`Clipe ${out.length+1}`,hook:c.text,reason:'Trecho forte identificado pela transcrição.',caption:c.text,hashtags:'#reels #cortes #viraclip',score:72-out.length*2})}while(out.length<count){const i=out.length,start=Math.max(0,(duration-d)*(count===1?0:i/(count-1)));out.push({start,end:Math.min(duration,start+d),title:`Clipe ${i+1}`,hook:'Momento selecionado automaticamente',reason:'Corte distribuído ao longo do vídeo.',caption:'Trecho selecionado do vídeo original.',hashtags:'#reels #cortes #viraclip',score:65-i})}return out}
async function chooseCuts(transcript,duration){const count=clamp(input.count||3,1,5),minD=clamp(input.minDuration||20,5,60),maxD=Math.max(minD,clamp(input.maxDuration||60,minD,60));const compact=transcript.segments.map(s=>`[${s.start.toFixed(1)}-${s.end.toFixed(1)}] ${s.text}`).join('\n').slice(0,14000);if(!compact)return fallbackCuts(duration,count,minD,maxD,transcript.segments);writeJob({stage:'selecting',percent:56,message:'IA escolhendo os melhores momentos'});const prompt=`Escolha exatamente ${count} cortes independentes para Reels, com maior potencial de retenção. Cada corte deve durar entre ${minD} e ${maxD} segundos e usar apenas tempos existentes entre 0 e ${duration.toFixed(1)}s. Responda somente JSON: {"clips":[{"start":0,"end":30,"title":"","hook":"","reason":"","caption":"","hashtags":"#reels","score":80}]}.\n${compact}`;try{const r=await fetchWithRetry('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${GROQ_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:TEXT_MODEL,messages:[{role:'user',content:prompt}],temperature:.2,response_format:{type:'json_object'}})},4);const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||`Groq ${r.status}`);let clips=JSON.parse(j?.choices?.[0]?.message?.content||'{}').clips||[];if(clips.length<count)throw new Error('Poucos cortes');return clips.slice(0,count).map((c,i)=>{let start=clamp(c.start,0,Math.max(0,duration-1)),end=clamp(c.end,start+1,duration);if(end-start<minD)end=Math.min(duration,start+minD);if(end-start>maxD)end=Math.min(duration,start+maxD);return{...c,start,end,title:clean(c.title||`Clipe ${i+1}`,100),hook:clean(c.hook||c.title,220),reason:clean(c.reason,400),caption:String(c.caption||'').slice(0,2200),hashtags:clean(c.hashtags||'#reels #viraclip',400),score:clamp(c.score||70,0,100)}})}catch(e){console.warn('Cloud worker fallback:',e.message);return fallbackCuts(duration,count,minD,maxD,transcript.segments)}}
async function uploadSrt(id,srt){const publicId=`viraclip/subtitles/${id}.srt`,form=new FormData();form.append('file',new Blob([Buffer.from(srt,'utf8')],{type:'application/x-subrip'}),`${id}.srt`);form.append('public_id',publicId);const auth=Buffer.from(`${CLOUD_KEY}:${CLOUD_SECRET}`).toString('base64');const r=await fetchWithRetry(`https://api.cloudinary.com/v1_1/${encodeURIComponent(CLOUD)}/raw/upload`,{method:'POST',headers:{Authorization:`Basic ${auth}`},body:form},4);const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||`Falha ao enviar legenda (${r.status})`);return j.public_id||publicId}
function clipUrl(sourceId,subId,start,end){const sid=String(subId).replace(/\//g,':');const transform=`so_${start.toFixed(2)},eo_${end.toFixed(2)}/c_fill,g_auto,w_720,h_1280/l_subtitles:Arial_20:${sid},co_white,bo_2px_solid_black/fl_layer_apply/q_auto:good,vc_h264`;return `https://res.cloudinary.com/${encodeURIComponent(CLOUD)}/video/upload/${transform}/${encodePublicId(sourceId)}.mp4`}
function saveProject(workspaceId,p){const created=now(),meta=JSON.stringify({viralScore:p.viralScore||0,reason:p.reason||'',clipStart:p.clipStart||0,clipEnd:p.clipEnd||0,sourceId:p.sourceId||'',renderer:'cloudinary'});db.prepare(`INSERT INTO projects(id,workspace_id,idea,hook,script,caption,hashtags,duration,status,video_url,planned_at,published_media_id,meta_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(p.id,workspaceId,p.idea||'',p.hook||'',p.script||'',p.caption||'',p.hashtags||'',Number(p.duration||0),'rendered',p.videoUrl,null,null,meta,created,created);return {...p,workspaceId,status:'rendered',createdAt:created,updatedAt:created,plannedAt:null,publishedMediaId:null,scenes:[{source:JSON.parse(meta)}]}}

(async()=>{try{if(!CLOUD||!CLOUD_KEY||!CLOUD_SECRET)throw new Error('Cloudinary não configurado');if(!GROQ_KEY)throw new Error('Groq não configurada');const publicId=input.cloudinaryPublicId||String(input.sourceId||'').replace(/^cloudinary:/,'');if(!publicId)throw new Error('Vídeo da nuvem não encontrado');const duration=Number(input.duration||0);if(!duration)throw new Error('Duração do vídeo ausente');writeJob({status:'running',stage:'starting',percent:28,message:'Processamento em nuvem iniciado'});const transcript=await transcribe(publicId);const cuts=await chooseCuts(transcript,duration),items=[];for(let i=0;i<cuts.length;i++){const c=cuts[i],id=uid('clip');writeJob({stage:'rendering',percent:68+Math.round(i*(28/cuts.length)),message:`Preparando clipe ${i+1}/${cuts.length} na nuvem`});const srt=makeSrt(transcript.segments,c.start,c.end,c.hook||c.title),subId=await uploadSrt(id,srt),videoUrl=clipUrl(publicId,subId,c.start,c.end),script=transcript.segments.filter(s=>s.end>=c.start&&s.start<=c.end).map(s=>s.text).join(' ')||c.hook||c.title;items.push(saveProject(input.workspaceId,{id,idea:c.title,hook:c.hook,script,caption:c.caption,hashtags:c.hashtags,duration:c.end-c.start,videoUrl,viralScore:c.score,reason:c.reason,clipStart:c.start,clipEnd:c.end,sourceId:publicId}));writeJob({stage:'rendering',percent:68+Math.round((i+1)*(28/cuts.length)),message:`Clipe ${i+1}/${cuts.length} preparado`})}writeJob({status:'done',stage:'done',percent:100,message:'Clipes prontos na nuvem',items,transcriptSegments:transcript.segments.length,finishedAt:now()})}catch(e){console.error(e);writeJob({status:'failed',stage:'failed',message:'Falha no processamento em nuvem',error:e.message||String(e),finishedAt:now()});process.exitCode=1}})();
