'use strict';

const previousFetch = globalThis.fetch.bind(globalThis);
const RESPONSES_URL = 'https://api.openai.com/v1/responses';
const MAX_SELECTION_CHARS = Number(process.env.GROQ_SELECTION_INPUT_CHARS || 16000);

function n(v, fallback = 0) { const x = Number(v); return Number.isFinite(x) ? x : fallback; }
function parseTranscriptLines(text) { return String(text || '').split('\n').map(line => { const m = line.match(/^\[(\d+(?:\.\d+)?)-(\d+(?:\.\d+)?)\]\s*(.*)$/); return m ? { start:n(m[1]), end:n(m[2]), text:m[3].trim() } : null; }).filter(Boolean); }
function lineScore(text) { const t=String(text||'').toLowerCase(); let s=Math.min(3,t.length/180); if(/[?!]/.test(t))s+=2; if(/\b\d+[\d.,%]*\b/.test(t))s+=1; if(/\b(você|vocês|como|porque|por quê|segredo|erro|nunca|sempre|ninguém|melhor|pior|verdade|descobri|aprendi|atenção|importante|problema|resultado|dinheiro|incrível|absurdo|olha|imagina|mas|então)\b/i.test(t))s+=2; return s; }
function buildBlocks(lines){const blocks=[];let cur=null;for(const seg of lines){if(!cur)cur={start:seg.start,end:seg.end,parts:[],score:0};cur.end=seg.end;cur.parts.push(seg.text);cur.score+=lineScore(seg.text);const span=cur.end-cur.start,chars=cur.parts.join(' ').length;if(span>=48||chars>=950){blocks.push({start:cur.start,end:cur.end,text:cur.parts.join(' '),score:cur.score});cur=null;}}if(cur&&cur.parts.length)blocks.push({start:cur.start,end:cur.end,text:cur.parts.join(' '),score:cur.score});return blocks;}
function compactPrompt(prompt){const marker='TRANSCRIÇÃO COM TEMPOS:\n',raw=String(prompt||''),idx=raw.indexOf(marker);if(idx<0||raw.length<=MAX_SELECTION_CHARS)return raw;const prefix=raw.slice(0,idx+marker.length),lines=parseTranscriptLines(raw.slice(idx+marker.length));if(!lines.length)return raw.slice(0,MAX_SELECTION_CHARS);const blocks=buildBlocks(lines),selected=new Map();[...blocks].sort((a,b)=>b.score-a.score).slice(0,12).forEach(b=>selected.set(`${b.start}-${b.end}`,b));const spreadCount=Math.min(8,blocks.length);for(let i=0;i<spreadCount;i++){const ix=Math.min(blocks.length-1,Math.round(i*(blocks.length-1)/Math.max(1,spreadCount-1))),b=blocks[ix];selected.set(`${b.start}-${b.end}`,b);}let out=prefix;for(const b of [...selected.values()].sort((a,b)=>a.start-b.start)){const row=`[${b.start.toFixed(1)}-${b.end.toFixed(1)}] ${b.text}\n`;if((out+row).length>MAX_SELECTION_CHARS)break;out+=row;}return out;}
function stripArrayLengthConstraints(node){if(!node||typeof node!=='object')return;delete node.minItems;delete node.maxItems;for(const value of Object.values(node)){if(Array.isArray(value))value.forEach(stripArrayLengthConstraints);else stripArrayLengthConstraints(value);}}
function requestMeta(prompt){const raw=String(prompt||''),count=Math.max(1,Math.min(10,n(raw.match(/Escolha exatamente (\d+)/)?.[1],3))),mm=raw.match(/entre (\d+(?:\.\d+)?) e (\d+(?:\.\d+)?) segundos/),minD=n(mm?.[1],20),maxD=Math.max(minD,n(mm?.[2],60)),dm=raw.match(/0 a (\d+(?:\.\d+)?)s/),duration=Math.max(maxD,n(dm?.[1],maxD*count));return{count,minD,maxD,duration};}
function fallbackClips(prompt){const meta=requestMeta(prompt),body=String(prompt).split('TRANSCRIÇÃO COM TEMPOS:\n')[1]||'',blocks=buildBlocks(parseTranscriptLines(body)).sort((a,b)=>b.score-a.score),chosen=[];for(const b of blocks){if(chosen.length>=meta.count)break;if(chosen.some(x=>Math.max(0,Math.min(x.end,b.end)-Math.max(x.start,b.start))>8))continue;let start=Math.max(0,b.start),end=Math.min(meta.duration,Math.max(b.end,start+meta.minD));if(end-start>meta.maxD)end=start+meta.maxD;if(end-start<meta.minD)start=Math.max(0,end-meta.minD);chosen.push({start,end,text:b.text});}while(chosen.length<meta.count){const d=Math.min(meta.maxD,Math.max(meta.minD,40)),usable=Math.max(0,meta.duration-d),i=chosen.length,start=meta.count>1?usable*i/(meta.count-1):0;chosen.push({start,end:Math.min(meta.duration,start+d),text:''});}return{clips:chosen.slice(0,meta.count).map((c,i)=>({start:Number(c.start.toFixed(1)),end:Number(c.end.toFixed(1)),title:`Clipe ${i+1}`,hook:c.text?c.text.slice(0,180):'Momento forte do vídeo',reason:'Seleção de segurança usada para manter o processamento funcionando quando a IA atinge um limite temporário.',caption:c.text?c.text.slice(0,500):'Trecho selecionado do vídeo original.',hashtags:'#reels #cortes #viraclip',score:Math.max(55,72-i*3)}))};}
function syntheticResponse(prompt,reason){console.warn('ViraClip selection fallback:',reason);const outputText=JSON.stringify(fallbackClips(prompt));return new Response(JSON.stringify({id:'resp_viraclip_fallback',object:'response',status:'completed',output_text:outputText,output:[{type:'message',status:'completed',content:[{type:'output_text',text:outputText}]}]}),{status:200,headers:{'content-type':'application/json'}});}

globalThis.fetch=async function viraClipSelectionSafeFetch(input,init={}){const url=typeof input==='string'?input:input instanceof URL?input.toString():input?.url;if(!url||!url.startsWith(RESPONSES_URL)||typeof init.body!=='string')return previousFetch(input,init);let body;try{body=JSON.parse(init.body)}catch{return previousFetch(input,init)}const originalPrompt=typeof body.input==='string'?body.input:'';body.input=compactPrompt(originalPrompt);body.reasoning={effort:'low'};if(body?.text?.format?.schema)stripArrayLengthConstraints(body.text.format.schema);const next={...init,body:JSON.stringify(body)};try{const response=await previousFetch(input,next);if(!response.ok){let detail=`HTTP ${response.status}`;try{const j=await response.clone().json();detail+=`: ${j?.error?.message||JSON.stringify(j).slice(0,500)}`}catch{}return syntheticResponse(body.input||originalPrompt,detail);}try{const j=await response.clone().json(),text=typeof j?.output_text==='string'?j.output_text:(j?.output||[]).flatMap(x=>x?.content||[]).find(x=>x?.type==='output_text')?.text,parsed=JSON.parse(text||'{}'),expected=requestMeta(originalPrompt).count;if(!Array.isArray(parsed?.clips)||parsed.clips.length<expected)return syntheticResponse(body.input||originalPrompt,'resposta incompleta da IA');}catch(e){return syntheticResponse(body.input||originalPrompt,`JSON inválido: ${e.message}`);}return response;}catch(e){return syntheticResponse(body.input||originalPrompt,`falha de rede: ${e.message}`);}};
