const http = require('http');
const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { spawnSync } = require('child_process');
const { DatabaseSync } = require('node:sqlite');

const PORT = Number(process.env.PORT || 3000);
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || '';
const OPENAI_TEXT_MODEL = process.env.OPENAI_TEXT_MODEL || 'gpt-5-mini';
const OPENAI_TRANSCRIBE_MODEL = process.env.OPENAI_TRANSCRIBE_MODEL || 'whisper-1';
const APP_SECRET = process.env.APP_SECRET || 'change-this-in-production';
const COOKIE_SECURE = String(process.env.COOKIE_SECURE || '').toLowerCase() === 'true';
const FFMPEG_BIN = process.env.FFMPEG_BIN || 'ffmpeg';
const FFPROBE_BIN = process.env.FFPROBE_BIN || 'ffprobe';
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
const MEDIA_DIR = process.env.MEDIA_DIR || path.join(DATA_DIR, 'media');
const UPLOAD_DIR = process.env.UPLOAD_DIR || path.join(DATA_DIR, 'uploads');
const DB_PATH = process.env.DATABASE_PATH || path.join(DATA_DIR, 'viraclip-v7.sqlite');
const PUBLIC_BASE_URL = String(process.env.PUBLIC_BASE_URL || '').replace(/\/$/, '');
const GLOBAL_IG_ID = process.env.INSTAGRAM_ACCOUNT_ID || '';
const GLOBAL_IG_TOKEN = process.env.INSTAGRAM_ACCESS_TOKEN || '';
const META_GRAPH_API_VERSION = process.env.META_GRAPH_API_VERSION || 'v24.0';
const ENABLE_YOUTUBE_IMPORT = String(process.env.ENABLE_YOUTUBE_IMPORT || '').toLowerCase() === 'true';
const MAX_UPLOAD = Number(process.env.MAX_UPLOAD_BYTES || 3 * 1024 * 1024 * 1024);

for (const d of [DATA_DIR, MEDIA_DIR, UPLOAD_DIR, path.dirname(DB_PATH)]) fs.mkdirSync(d, { recursive: true });
const db = new DatabaseSync(DB_PATH);
db.exec(`
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,salt TEXT NOT NULL,hash TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS workspaces(id TEXT PRIMARY KEY,name TEXT NOT NULL,owner_user_id TEXT NOT NULL,instagram_account_id TEXT,instagram_token_enc TEXT,instagram_token_iv TEXT,instagram_token_tag TEXT,graph_version TEXT,public_base_url TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS memberships(user_id TEXT NOT NULL,workspace_id TEXT NOT NULL,role TEXT NOT NULL,PRIMARY KEY(user_id,workspace_id));
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,idea TEXT,hook TEXT,script TEXT,caption TEXT,hashtags TEXT,duration REAL,status TEXT,video_url TEXT,planned_at TEXT,published_media_id TEXT,meta_json TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS schedules(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,project_id TEXT,video_url TEXT NOT NULL,caption TEXT,share_to_feed INTEGER NOT NULL DEFAULT 1,publish_at TEXT NOT NULL,status TEXT NOT NULL,error TEXT,media_id TEXT,created_at TEXT NOT NULL,published_at TEXT);
CREATE TABLE IF NOT EXISTS analytics(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,project_id TEXT,media_id TEXT,captured_at TEXT NOT NULL,views REAL DEFAULT 0,reach REAL DEFAULT 0,likes REAL DEFAULT 0,comments REAL DEFAULT 0,shares REAL DEFAULT 0,saved REAL DEFAULT 0,total_interactions REAL DEFAULT 0,avg_watch_time REAL DEFAULT 0,total_watch_time REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS strategy(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,summary TEXT NOT NULL,recommendations_json TEXT NOT NULL,created_at TEXT NOT NULL);
`);

const MIME = {'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.mp4':'video/mp4','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'};
const now = () => new Date().toISOString();
const uid = p => `${p}_${crypto.randomBytes(10).toString('hex')}`;
const clean = (v, n=4000) => String(v ?? '').replace(/\s+/g,' ').trim().slice(0,n);
const sleep = ms => new Promise(r => setTimeout(r, ms));
const clamp = (n,a,b) => Math.max(a,Math.min(b,Number(n)||0));
function sendJson(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(body)});res.end(body)}
function readBody(req,limit=256*1024){return new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(Buffer.byteLength(data)>limit){reject(new Error('Payload muito grande'));req.destroy()}});req.on('end',()=>{try{resolve(data?JSON.parse(data):{})}catch{reject(new Error('JSON inválido'))}});req.on('error',reject)})}
function run(bin,args){const r=spawnSync(bin,args,{encoding:'utf8',maxBuffer:32*1024*1024});if(r.status!==0)throw new Error((r.stderr||r.stdout||`Falha em ${bin}`).trim());return r.stdout||''}
function exists(bin){try{return spawnSync(bin,['-version'],{stdio:'ignore'}).status===0}catch{return false}}
function parseCookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return [decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}))}
function setSessionCookie(res,id){const parts=[`viraclip_session=${encodeURIComponent(id)}`,'Path=/','HttpOnly','SameSite=Lax','Max-Age=2592000'];if(COOKIE_SECURE)parts.push('Secure');res.setHeader('Set-Cookie',parts.join('; '))}
function clearSessionCookie(res){res.setHeader('Set-Cookie','viraclip_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0')}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return {salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}
function verifyPassword(password,salt,hash){const got=crypto.scryptSync(password,salt,64);const exp=Buffer.from(hash,'hex');return got.length===exp.length&&crypto.timingSafeEqual(got,exp)}
function sessionUser(req){const id=parseCookies(req).viraclip_session;if(!id)return null;const row=db.prepare(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?`).get(id,now());return row||null}
function createSession(res,userId){const id=uid('sess'),created=now(),expires=new Date(Date.now()+30*86400000).toISOString();db.prepare('INSERT INTO sessions(id,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(id,userId,expires,created);setSessionCookie(res,id);return id}
function userWorkspaces(userId){return db.prepare(`SELECT w.id,w.name,m.role FROM memberships m JOIN workspaces w ON w.id=m.workspace_id WHERE m.user_id=? ORDER BY w.created_at`).all(userId)}
function workspaceFor(req,user){const id=String(req.headers['x-workspace-id']||'');if(!id)return null;return db.prepare(`SELECT w.*,m.role FROM workspaces w JOIN memberships m ON m.workspace_id=w.id WHERE w.id=? AND m.user_id=?`).get(id,user.id)||null}
function secretKey(){return crypto.createHash('sha256').update(APP_SECRET).digest()}
function encryptSecret(value){if(!value)return {enc:null,iv:null,tag:null};const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',secretKey(),iv);const enc=Buffer.concat([c.update(value,'utf8'),c.final()]);return {enc:enc.toString('base64'),iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64')}}
function decryptSecret(enc,iv,tag){if(!enc||!iv||!tag)return '';try{const d=crypto.createDecipheriv('aes-256-gcm',secretKey(),Buffer.from(iv,'base64'));d.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([d.update(Buffer.from(enc,'base64')),d.final()]).toString('utf8')}catch{return ''}}
function instagramConfig(ws){return {accountId:ws.instagram_account_id||GLOBAL_IG_ID,accessToken:decryptSecret(ws.instagram_token_enc,ws.instagram_token_iv,ws.instagram_token_tag)||GLOBAL_IG_TOKEN,graphVersion:ws.graph_version||META_GRAPH_API_VERSION,baseUrl:String(ws.public_base_url||PUBLIC_BASE_URL||'').replace(/\/$/,'')}}

function mapProject(r){if(!r)return null;let meta={};try{meta=JSON.parse(r.meta_json||'{}')}catch{}return {id:r.id,workspaceId:r.workspace_id,idea:r.idea,hook:r.hook,script:r.script,caption:r.caption,hashtags:r.hashtags,duration:Number(r.duration||0),status:r.status,videoUrl:r.video_url,plannedAt:r.planned_at,publishedMediaId:r.published_media_id,viralScore:Number(meta.viralScore||0),reason:meta.reason||'',clipStart:Number(meta.clipStart||0),clipEnd:Number(meta.clipEnd||0),scenes:[{source:meta}],createdAt:r.created_at,updatedAt:r.updated_at}}
function listProjects(workspaceId,limit=200){return db.prepare('SELECT * FROM projects WHERE workspace_id=? ORDER BY created_at DESC LIMIT ?').all(workspaceId,limit).map(mapProject)}
function getProject(workspaceId,id){return mapProject(db.prepare('SELECT * FROM projects WHERE workspace_id=? AND id=?').get(workspaceId,id))}
function saveProject(workspaceId,p,meta={}){const id=p.id||uid('clip'),created=p.createdAt||now(),updated=now();const existing=db.prepare('SELECT id FROM projects WHERE id=? AND workspace_id=?').get(id,workspaceId);const mj=JSON.stringify({viralScore:p.viralScore??meta.viralScore??0,reason:p.reason??meta.reason??'',clipStart:p.clipStart??meta.clipStart??0,clipEnd:p.clipEnd??meta.clipEnd??0,sourceId:p.sourceId??meta.sourceId??''});if(existing)db.prepare(`UPDATE projects SET idea=?,hook=?,script=?,caption=?,hashtags=?,duration=?,status=?,video_url=?,planned_at=?,published_media_id=?,meta_json=?,updated_at=? WHERE id=? AND workspace_id=?`).run(p.idea||'',p.hook||'',p.script||'',p.caption||'',p.hashtags||'',Number(p.duration||0),p.status||'rendered',p.videoUrl||null,p.plannedAt||null,p.publishedMediaId||null,mj,updated,id,workspaceId);else db.prepare(`INSERT INTO projects(id,workspace_id,idea,hook,script,caption,hashtags,duration,status,video_url,planned_at,published_media_id,meta_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,workspaceId,p.idea||'',p.hook||'',p.script||'',p.caption||'',p.hashtags||'',Number(p.duration||0),p.status||'rendered',p.videoUrl||null,p.plannedAt||null,p.publishedMediaId||null,mj,created,updated);return getProject(workspaceId,id)}

function safeFileName(v){return path.basename(decodeURIComponent(String(v||'video.mp4'))).replace(/[^a-zA-Z0-9._ -]/g,'_').slice(0,180)||'video.mp4'}
function extFor(name,type=''){const ext=path.extname(name).toLowerCase();if(['.mp4','.mov','.m4v','.webm','.mkv','.avi'].includes(ext))return ext;return type.includes('webm')?'.webm':type.includes('quicktime')?'.mov':'.mp4'}
function receiveUpload(req,filePath){return new Promise((resolve,reject)=>{let bytes=0;const out=fs.createWriteStream(filePath);const fail=e=>{out.destroy();fs.rm(filePath,{force:true},()=>{});reject(e)};req.on('data',c=>{bytes+=c.length;if(bytes>MAX_UPLOAD){fail(new Error('Vídeo excede o limite de upload'));req.destroy()}});req.on('error',fail);out.on('error',fail);out.on('finish',()=>resolve(bytes));req.pipe(out)})}
function probe(file){const raw=run(FFPROBE_BIN,['-v','error','-print_format','json','-show_format','-show_streams',file]);const j=JSON.parse(raw),v=(j.streams||[]).find(x=>x.codec_type==='video')||{};return {duration:Number(j.format?.duration||v.duration||0),width:Number(v.width||0),height:Number(v.height||0)}}
function findSource(sourceId){const f=fs.readdirSync(UPLOAD_DIR).find(x=>x.startsWith(`${sourceId}.`)||x.startsWith(`${sourceId}_`));return f?path.join(UPLOAD_DIR,f):null}
function srtTime(sec){const ms=Math.max(0,Math.round(Number(sec||0)*1000)),h=String(Math.floor(ms/3600000)).padStart(2,'0'),m=String(Math.floor(ms%3600000/60000)).padStart(2,'0'),s=String(Math.floor(ms%60000/1000)).padStart(2,'0'),x=String(ms%1000).padStart(3,'0');return `${h}:${m}:${s},${x}`}
function writeSrt(file,segments,start,end,fallback){const rows=[];for(const seg of segments||[]){const a=Math.max(start,Number(seg.start||0)),b=Math.min(end,Number(seg.end||0));if(b-a<.08)continue;rows.push(`${rows.length+1}\n${srtTime(a-start)} --> ${srtTime(b-start)}\n${String(seg.text||'').trim()}\n`)}if(!rows.length&&fallback)rows.push(`1\n00:00:00,000 --> ${srtTime(Math.max(.5,end-start))}\n${fallback}\n`);fs.writeFileSync(file,rows.join('\n'),'utf8')}
function subtitleFilter(srt){const escaped=srt.replace(/\\/g,'/').replace(/:/g,'\\:').replace(/'/g,"\\'");return `scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,setsar=1,subtitles='${escaped}':force_style='FontName=Arial,FontSize=20,PrimaryColour=&H00FFFFFF,OutlineColour=&H00000000,BorderStyle=1,Outline=3,Shadow=1,Alignment=2,MarginV=140'`}
function renderClip(source,start,end,projectId,segments,hook){const duration=Math.max(1,end-start),srt=path.join(os.tmpdir(),`${projectId}.srt`),out=path.join(MEDIA_DIR,`${projectId}.mp4`);writeSrt(srt,segments,start,end,hook);try{run(FFMPEG_BIN,['-y','-loglevel','error','-ss',String(start),'-t',String(duration),'-i',source,'-vf',subtitleFilter(srt),'-map','0:v:0','-map','0:a?','-c:v','libx264','-preset','veryfast','-crf','23','-c:a','aac','-b:a','128k','-movflags','+faststart',out])}finally{fs.rmSync(srt,{force:true})}return `/media/${path.basename(out)}`}

async function transcribe(source){if(!OPENAI_API_KEY)return {text:'',segments:[]};const dir=fs.mkdtempSync(path.join(os.tmpdir(),'viraclip-audio-'));try{const pattern=path.join(dir,'chunk-%03d.mp3');run(FFMPEG_BIN,['-y','-loglevel','error','-i',source,'-vn','-ac','1','-ar','16000','-b:a','48k','-f','segment','-segment_time','600','-reset_timestamps','1',pattern]);const files=fs.readdirSync(dir).filter(x=>x.endsWith('.mp3')).sort(),segments=[];let offset=0;for(const name of files){const fp=path.join(dir,name),info=probeAudio(fp);const form=new FormData();form.append('file',new Blob([fs.readFileSync(fp)],{type:'audio/mpeg'}),name);form.append('model',OPENAI_TRANSCRIBE_MODEL);form.append('language','pt');form.append('response_format','verbose_json');form.append('timestamp_granularities[]','segment');const r=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_API_KEY}`},body:form});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||'Falha na transcrição');for(const s of j.segments||[])segments.push({start:offset+Number(s.start||0),end:offset+Number(s.end||0),text:String(s.text||'').trim()});offset+=info}return {text:segments.map(s=>s.text).join(' '),segments}}finally{fs.rmSync(dir,{recursive:true,force:true})}}
function probeAudio(file){const x=Number(run(FFPROBE_BIN,['-v','error','-show_entries','format=duration','-of','default=nw=1:nk=1',file]).trim());return Number.isFinite(x)?x:600}
function extractResponseText(j){if(typeof j?.output_text==='string')return j.output_text;for(const item of j?.output||[])for(const c of item?.content||[])if(c?.type==='output_text'&&typeof c.text==='string')return c.text;return ''}
function fallbackCuts(duration,count,minD,maxD){const d=clamp(Math.min(maxD,Math.max(minD,45)),5,Math.max(5,duration));const usable=Math.max(0,duration-d),step=count>1?usable/(count-1):0;return Array.from({length:count},(_,i)=>{const start=Math.min(usable,i*step),end=Math.min(duration,start+d);return {start,end,title:`Clipe ${i+1}`,hook:'Momento selecionado automaticamente',reason:'Corte distribuído ao longo do vídeo.',caption:'Trecho do vídeo original.',hashtags:'#reels #cortes #viraclip',score:60-i}})}
async function chooseCuts(transcript,duration,opt){const count=clamp(opt.count||5,1,10),minD=clamp(opt.minDuration||20,5,90),maxD=Math.max(minD,clamp(opt.maxDuration||60,minD,180));if(!OPENAI_API_KEY||!transcript.segments.length)return fallbackCuts(duration,count,minD,maxD);const compact=transcript.segments.map(s=>`[${s.start.toFixed(1)}-${s.end.toFixed(1)}] ${s.text}`).join('\n').slice(0,80000);const schema={type:'object',additionalProperties:false,properties:{clips:{type:'array',minItems:count,maxItems:count,items:{type:'object',additionalProperties:false,properties:{start:{type:'number'},end:{type:'number'},title:{type:'string'},hook:{type:'string'},reason:{type:'string'},caption:{type:'string'},hashtags:{type:'string'},score:{type:'number'}},required:['start','end','title','hook','reason','caption','hashtags','score']}}},required:['clips']};const prompt=`Você é editor de vídeos curtos. Escolha exatamente ${count} cortes independentes com maior potencial de retenção. Objetivo: ${clean(opt.goal||'Maior retenção',80)}. Cada corte deve durar entre ${minD} e ${maxD} segundos, começar e terminar em pontos naturais da fala, evitar sobreposição forte, não inventar conteúdo e usar apenas tempos existentes no vídeo (0 a ${duration.toFixed(1)}s). Retorne títulos curtos, hook, motivo, legenda, hashtags e score 0-100.\nTRANSCRIÇÃO COM TEMPOS:\n${compact}`;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:OPENAI_TEXT_MODEL,input:prompt,text:{format:{type:'json_schema',name:'viraclip_cuts',strict:true,schema}}})});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||'Falha ao selecionar cortes');let clips=JSON.parse(extractResponseText(j)).clips||[];clips=clips.map((c,i)=>{let start=clamp(c.start,0,Math.max(0,duration-1)),end=clamp(c.end,start+1,duration);if(end-start<minD)end=Math.min(duration,start+minD);if(end-start>maxD)end=start+maxD;return {...c,start,end,score:clamp(c.score,0,100),title:clean(c.title||`Clipe ${i+1}`,100),hook:clean(c.hook,240),reason:clean(c.reason,500),caption:String(c.caption||'').trim().slice(0,2200),hashtags:clean(c.hashtags,500)}});return clips.slice(0,count)}
async function createClips(ws,sourceId,opt){const source=findSource(sourceId);if(!source)throw new Error('Vídeo fonte não encontrado. Faça o upload novamente.');const info=probe(source);if(!info.duration)throw new Error('Não foi possível ler a duração do vídeo.');const transcript=await transcribe(source),cuts=await chooseCuts(transcript,info.duration,opt),items=[];for(const [i,c] of cuts.entries()){const id=uid('clip'),videoUrl=renderClip(source,c.start,c.end,id,transcript.segments,c.hook||c.title),script=transcript.segments.filter(s=>s.end>=c.start&&s.start<=c.end).map(s=>s.text).join(' ')||c.hook||c.title;items.push(saveProject(ws.id,{id,idea:c.title||`Clipe ${i+1}`,hook:c.hook||c.title,script,caption:c.caption||'',hashtags:c.hashtags||'',duration:c.end-c.start,status:'rendered',videoUrl,viralScore:c.score,reason:c.reason,clipStart:c.start,clipEnd:c.end,sourceId}))}return {items,transcriptSegments:transcript.segments.length}}

async function graphJson(url,options={}){const r=await fetch(url,options);const j=await r.json();if(!r.ok||j.error)throw new Error(j?.error?.message||`Meta HTTP ${r.status}`);return j}
function absoluteVideoUrl(ws,url){if(/^https:\/\//i.test(url||''))return url;const base=instagramConfig(ws).baseUrl;if(!base)throw new Error('Configure a URL pública HTTPS nas Integrações');if(!/^https:\/\//i.test(base))throw new Error('A URL pública precisa usar HTTPS');return `${base}${String(url||'').startsWith('/')?'':'/'}${url}`}
async function publishInstagram(ws,{videoUrl,caption,shareToFeed=true}){const cfg=instagramConfig(ws);if(!cfg.accountId||!cfg.accessToken)throw new Error('Configure o Instagram deste perfil primeiro');const publicUrl=absoluteVideoUrl(ws,videoUrl);const base=`https://graph.facebook.com/${cfg.graphVersion}`;const create=new URLSearchParams({media_type:'REELS',video_url:publicUrl,caption:String(caption||''),share_to_feed:shareToFeed?'true':'false',access_token:cfg.accessToken});const c=await graphJson(`${base}/${cfg.accountId}/media`,{method:'POST',body:create});for(let i=0;i<30;i++){await sleep(4000);const s=await graphJson(`${base}/${c.id}?fields=status_code,status&access_token=${encodeURIComponent(cfg.accessToken)}`);if(s.status_code==='FINISHED')break;if(['ERROR','EXPIRED'].includes(s.status_code))throw new Error(s.status||'Falha ao processar Reel');if(i===29)throw new Error('A Meta demorou demais para processar o vídeo')}const p=new URLSearchParams({creation_id:c.id,access_token:cfg.accessToken});const pub=await graphJson(`${base}/${cfg.accountId}/media_publish`,{method:'POST',body:p});return {mediaId:pub.id,containerId:c.id}}
async function refreshAnalytics(ws){const cfg=instagramConfig(ws);if(!cfg.accountId||!cfg.accessToken)throw new Error('Configure o Instagram deste perfil primeiro');const projects=listProjects(ws.id,100).filter(p=>p.publishedMediaId);let refreshed=0;for(const p of projects){let views=0,reach=0,likes=0,comments=0,shares=0,saved=0,total=0;try{const f=await graphJson(`https://graph.facebook.com/${cfg.graphVersion}/${p.publishedMediaId}?fields=like_count,comments_count&access_token=${encodeURIComponent(cfg.accessToken)}`);likes=Number(f.like_count||0);comments=Number(f.comments_count||0)}catch{}try{const x=await graphJson(`https://graph.facebook.com/${cfg.graphVersion}/${p.publishedMediaId}/insights?metric=views,reach,total_interactions,saved,shares&access_token=${encodeURIComponent(cfg.accessToken)}`);const m=Object.fromEntries((x.data||[]).map(a=>[a.name,Number(a.values?.[0]?.value??a.value??0)]));views=m.views||0;reach=m.reach||0;shares=m.shares||0;saved=m.saved||0;total=m.total_interactions||likes+comments+shares+saved}catch{total=likes+comments}db.prepare(`INSERT INTO analytics(id,workspace_id,project_id,media_id,captured_at,views,reach,likes,comments,shares,saved,total_interactions) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(uid('metric'),ws.id,p.id,p.publishedMediaId,now(),views,reach,likes,comments,shares,saved,total);refreshed++}return refreshed}
function analyticsDashboard(workspaceId){const rows=db.prepare('SELECT * FROM analytics WHERE workspace_id=? ORDER BY captured_at DESC').all(workspaceId),latest=new Map();for(const r of rows)if(!latest.has(r.project_id))latest.set(r.project_id,r);const items=listProjects(workspaceId,200).map(p=>{const m=latest.get(p.id);return {...p,metrics:m?{capturedAt:m.captured_at,views:Number(m.views||0),reach:Number(m.reach||0),likes:Number(m.likes||0),comments:Number(m.comments||0),shares:Number(m.shares||0),saved:Number(m.saved||0),interactions:Number(m.total_interactions||0),engagementRate:Number(m.reach||0)?Number(m.total_interactions||0)/Number(m.reach):0,retentionProxy:Number(m.views||0)&&p.duration?Math.min(1,Number(m.avg_watch_time||0)/p.duration):0}:null}});const summary=items.reduce((a,p)=>{const m=p.metrics;if(!m)return a;a.views+=m.views;a.reach+=m.reach;a.interactions+=m.interactions;return a},{views:0,reach:0,interactions:0});summary.engagementRate=summary.reach?summary.interactions/summary.reach:0;return {summary,items}}
function latestStrategy(workspaceId){const r=db.prepare('SELECT * FROM strategy WHERE workspace_id=? ORDER BY created_at DESC LIMIT 1').get(workspaceId);if(!r)return {summary:'Ainda não há dados suficientes.',recommendations:[]};let recommendations=[];try{recommendations=JSON.parse(r.recommendations_json)}catch{}return {summary:r.summary,recommendations,createdAt:r.created_at}}
function buildStrategy(workspaceId){const d=analyticsDashboard(workspaceId),ranked=d.items.filter(x=>x.metrics).sort((a,b)=>(b.metrics.engagementRate||0)-(a.metrics.engagementRate||0));let summary='Ainda não há dados suficientes.',recommendations=['Teste ganchos mais diretos nos primeiros segundos.','Compare cortes de 20–45 segundos com cortes mais longos.','Repita temas que gerarem mais compartilhamentos e salvamentos.'];if(ranked.length){summary=`Melhor corte atual: ${ranked[0].idea||'Clipe'} com ${(ranked[0].metrics.engagementRate*100).toFixed(1)}% de interação por alcance.`;recommendations=[`Use como referência o ritmo do corte “${ranked[0].idea||'melhor corte'}”.`,'Priorize trechos que começam com uma frase completa e forte.','Evite introduções longas antes do ponto principal.']}const s={id:uid('strategy'),workspaceId,summary,recommendations,createdAt:now()};db.prepare('INSERT INTO strategy(id,workspace_id,summary,recommendations_json,created_at) VALUES(?,?,?,?,?)').run(s.id,workspaceId,summary,JSON.stringify(recommendations),s.createdAt);return s}

async function processSchedules(){const due=db.prepare(`SELECT * FROM schedules WHERE status='scheduled' AND publish_at<=? ORDER BY publish_at LIMIT 5`).all(now());for(const s of due){try{db.prepare(`UPDATE schedules SET status='publishing',error=NULL WHERE id=?`).run(s.id);const ws=db.prepare('SELECT * FROM workspaces WHERE id=?').get(s.workspace_id),result=await publishInstagram(ws,{videoUrl:s.video_url,caption:s.caption,shareToFeed:Boolean(s.share_to_feed)});db.prepare(`UPDATE schedules SET status='published',media_id=?,published_at=? WHERE id=?`).run(result.mediaId,now(),s.id);if(s.project_id)db.prepare(`UPDATE projects SET status='published',published_media_id=?,updated_at=? WHERE id=?`).run(result.mediaId,now(),s.project_id)}catch(e){db.prepare(`UPDATE schedules SET status='failed',error=? WHERE id=?`).run(String(e.message||e).slice(0,1000),s.id)}}}
setInterval(()=>processSchedules().catch(console.error),60000).unref();

function serveFile(res,file){if(!fs.existsSync(file)||!fs.statSync(file).isFile())return false;const ext=path.extname(file).toLowerCase();res.writeHead(200,{'Content-Type':MIME[ext]||'application/octet-stream','Content-Length':fs.statSync(file).size,'Cache-Control':ext==='.mp4'?'public, max-age=3600':'no-cache'});fs.createReadStream(file).pipe(res);return true}
function serveStatic(req,res,pathname){if(pathname.startsWith('/media/')){const name=path.basename(pathname);if(serveFile(res,path.join(MEDIA_DIR,name)))return true;sendJson(res,404,{error:'Mídia não encontrada'});return true}const rel=pathname==='/'?'index.html':pathname.replace(/^\//,'');const file=path.join(__dirname,rel);if(!file.startsWith(__dirname)||!['index.html','app.js','styles.css'].includes(rel)){sendJson(res,404,{error:'Não encontrado'});return true}if(!serveFile(res,file))sendJson(res,404,{error:'Não encontrado'});return true}

const server=http.createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;try{
  if(req.method==='GET'&&pathname==='/api/status')return sendJson(res,200,{version:'7.0.0',aiConfigured:Boolean(OPENAI_API_KEY),transcriptionConfigured:Boolean(OPENAI_API_KEY),ffmpegAvailable:exists(FFMPEG_BIN)&&exists(FFPROBE_BIN),youtubeImportEnabled:ENABLE_YOUTUBE_IMPORT,graphVersion:META_GRAPH_API_VERSION,database:'sqlite',auth:true});
  if(req.method==='POST'&&pathname==='/api/auth/register'){const b=await readBody(req,64*1024),name=clean(b.name,100),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),workspaceName=clean(b.workspaceName||'Meu perfil',100);if(!name||!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return sendJson(res,400,{error:'Preencha nome, e-mail válido e senha com pelo menos 8 caracteres'});if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return sendJson(res,409,{error:'Este e-mail já está cadastrado'});const userId=uid('user'),wsId=uid('ws'),hp=hashPassword(password),created=now();db.exec('BEGIN');try{db.prepare('INSERT INTO users(id,name,email,salt,hash,created_at) VALUES(?,?,?,?,?,?)').run(userId,name,email,hp.salt,hp.hash,created);db.prepare('INSERT INTO workspaces(id,name,owner_user_id,graph_version,created_at) VALUES(?,?,?,?,?)').run(wsId,workspaceName,userId,META_GRAPH_API_VERSION,created);db.prepare('INSERT INTO memberships(user_id,workspace_id,role) VALUES(?,?,?)').run(userId,wsId,'owner');db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}createSession(res,userId);return sendJson(res,200,{ok:true})}
  if(req.method==='POST'&&pathname==='/api/auth/login'){const b=await readBody(req,32*1024),email=String(b.email||'').trim().toLowerCase(),u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!verifyPassword(String(b.password||''),u.salt,u.hash))return sendJson(res,401,{error:'E-mail ou senha inválidos'});createSession(res,u.id);return sendJson(res,200,{ok:true})}
  if(req.method==='POST'&&pathname==='/api/auth/logout'){const id=parseCookies(req).viraclip_session;if(id)db.prepare('DELETE FROM sessions WHERE id=?').run(id);clearSessionCookie(res);return sendJson(res,200,{ok:true})}
  const user=sessionUser(req);
  if(req.method==='GET'&&pathname==='/api/me'){if(!user)return sendJson(res,401,{error:'Faça login'});return sendJson(res,200,{user:{id:user.id,name:user.name,email:user.email},workspaces:userWorkspaces(user.id)})}
  if(req.method==='GET'&&!pathname.startsWith('/api/'))return serveStatic(req,res,pathname);
  if(!user)return sendJson(res,401,{error:'Faça login'});
  if(req.method==='GET'&&pathname==='/api/workspaces')return sendJson(res,200,{items:userWorkspaces(user.id)});
  if(req.method==='POST'&&pathname==='/api/workspaces'){const b=await readBody(req,32*1024),name=clean(b.name,100);if(!name)return sendJson(res,400,{error:'Digite o nome do perfil'});const id=uid('ws'),created=now();db.prepare('INSERT INTO workspaces(id,name,owner_user_id,graph_version,created_at) VALUES(?,?,?,?,?)').run(id,name,user.id,META_GRAPH_API_VERSION,created);db.prepare('INSERT INTO memberships(user_id,workspace_id,role) VALUES(?,?,?)').run(user.id,id,'owner');return sendJson(res,200,{id,name,role:'owner'})}
  const ws=workspaceFor(req,user);if(!ws)return sendJson(res,400,{error:'Selecione um perfil/cliente válido'});
  if(req.method==='GET'&&pathname==='/api/workspace-status'){const c=instagramConfig(ws);return sendJson(res,200,{workspace:{id:ws.id,name:ws.name,role:ws.role},instagramConfigured:Boolean(c.accountId&&c.accessToken),publicBaseUrlConfigured:Boolean(c.baseUrl)})}
  if(req.method==='GET'&&pathname==='/api/integrations/instagram'){const c=instagramConfig(ws);return sendJson(res,200,{accountId:ws.instagram_account_id||'',hasToken:Boolean(c.accessToken),graphVersion:ws.graph_version||META_GRAPH_API_VERSION,publicBaseUrl:ws.public_base_url||PUBLIC_BASE_URL||'',usingGlobalCredentials:Boolean(!ws.instagram_account_id&&GLOBAL_IG_ID)})}
  if(req.method==='PUT'&&pathname==='/api/integrations/instagram'){if(ws.role!=='owner')return sendJson(res,403,{error:'Somente o proprietário pode alterar integrações'});const b=await readBody(req,64*1024),accountId=clean(b.accountId,120),token=String(b.accessToken||''),graphVersion=clean(b.graphVersion||META_GRAPH_API_VERSION,20),baseUrl=clean(b.publicBaseUrl,300).replace(/\/$/,'');let sec={enc:ws.instagram_token_enc,iv:ws.instagram_token_iv,tag:ws.instagram_token_tag};if(token)sec=encryptSecret(token);db.prepare('UPDATE workspaces SET instagram_account_id=?,instagram_token_enc=?,instagram_token_iv=?,instagram_token_tag=?,graph_version=?,public_base_url=? WHERE id=?').run(accountId||null,sec.enc,sec.iv,sec.tag,graphVersion,baseUrl||null,ws.id);return sendJson(res,200,{ok:true})}
  if(req.method==='POST'&&pathname==='/api/source-upload'){if(!exists(FFMPEG_BIN)||!exists(FFPROBE_BIN))return sendJson(res,503,{error:'FFmpeg/FFprobe indisponível'});const original=safeFileName(req.headers['x-file-name']||'video.mp4'),sourceId=uid('source'),ext=extFor(original,String(req.headers['content-type']||'')),fp=path.join(UPLOAD_DIR,`${sourceId}${ext}`),bytes=await receiveUpload(req,fp);let info;try{info=probe(fp)}catch{fs.rmSync(fp,{force:true});throw new Error('Arquivo de vídeo inválido ou não suportado')}return sendJson(res,200,{sourceId,fileName:original,bytes,...info})}
  if(req.method==='POST'&&pathname==='/api/import-youtube'){const b=await readBody(req,32*1024);if(!b.rightsConfirmed)return sendJson(res,400,{error:'Confirme que você tem autorização para reutilizar o vídeo'});if(!ENABLE_YOUTUBE_IMPORT)return sendJson(res,501,{error:'Importação por link está desativada. Use o upload direto por enquanto.'});return sendJson(res,501,{error:'Importador autorizado ainda não configurado neste servidor.'})}
  if(req.method==='POST'&&pathname==='/api/clip-source'){const b=await readBody(req,64*1024),result=await createClips(ws,String(b.sourceId||''),b);return sendJson(res,200,result)}
  if(req.method==='GET'&&pathname==='/api/projects')return sendJson(res,200,{items:listProjects(ws.id,200)});
  if(req.method==='POST'&&pathname==='/api/publish-instagram'){const b=await readBody(req,64*1024),p=b.projectId?getProject(ws.id,b.projectId):null,videoUrl=b.videoUrl||p?.videoUrl,caption=b.caption??p?.caption??'';if(!videoUrl)return sendJson(res,400,{error:'Selecione um clipe renderizado'});const result=await publishInstagram(ws,{videoUrl,caption,shareToFeed:b.shareToFeed!==false});if(p)saveProject(ws.id,{...p,status:'published',publishedMediaId:result.mediaId});return sendJson(res,200,result)}
  if(req.method==='GET'&&pathname==='/api/schedules'){const items=db.prepare('SELECT * FROM schedules WHERE workspace_id=? ORDER BY publish_at DESC LIMIT 200').all(ws.id).map(x=>({id:x.id,projectId:x.project_id,videoUrl:x.video_url,caption:x.caption,shareToFeed:Boolean(x.share_to_feed),publishAt:x.publish_at,status:x.status,error:x.error,mediaId:x.media_id,createdAt:x.created_at,publishedAt:x.published_at}));return sendJson(res,200,{items})}
  if(req.method==='POST'&&pathname==='/api/schedules'){const b=await readBody(req,64*1024),p=b.projectId?getProject(ws.id,b.projectId):null,videoUrl=b.videoUrl||p?.videoUrl,d=new Date(b.publishAt);if(!videoUrl)return sendJson(res,400,{error:'Selecione um clipe renderizado'});if(!Number.isFinite(d.getTime())||d.getTime()<=Date.now())return sendJson(res,400,{error:'Escolha uma data futura válida'});const id=uid('schedule'),caption=b.caption??p?.caption??'';db.prepare('INSERT INTO schedules(id,workspace_id,project_id,video_url,caption,share_to_feed,publish_at,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,ws.id,p?.id||null,videoUrl,caption,b.shareToFeed===false?0:1,d.toISOString(),'scheduled',now());if(p)saveProject(ws.id,{...p,plannedAt:d.toISOString()});return sendJson(res,200,{id,publishAt:d.toISOString(),status:'scheduled'})}
  if(req.method==='GET'&&pathname==='/api/calendar'){const u=new URL(req.url,'http://localhost'),from=u.searchParams.get('from')||new Date(Date.now()-7*86400000).toISOString(),to=u.searchParams.get('to')||new Date(Date.now()+45*86400000).toISOString(),schedules=db.prepare('SELECT * FROM schedules WHERE workspace_id=? AND publish_at BETWEEN ? AND ? ORDER BY publish_at').all(ws.id,from,to),planned=db.prepare('SELECT * FROM projects WHERE workspace_id=? AND planned_at BETWEEN ? AND ? ORDER BY planned_at').all(ws.id,from,to).map(mapProject);return sendJson(res,200,{schedules,planned})}
  if(req.method==='GET'&&pathname==='/api/analytics')return sendJson(res,200,{...analyticsDashboard(ws.id),strategy:latestStrategy(ws.id)});
  if(req.method==='POST'&&pathname==='/api/analytics/demo'){const projects=listProjects(ws.id,20);if(!projects.length)return sendJson(res,400,{error:'Crie pelo menos um clipe antes'});for(const [i,p] of projects.slice(0,6).entries()){const reach=800+i*430,views=Math.round(reach*1.3),likes=45+i*14,comments=5+i*2,shares=8+i*3,saved=12+i*4,total=likes+comments+shares+saved;db.prepare('INSERT INTO analytics(id,workspace_id,project_id,media_id,captured_at,views,reach,likes,comments,shares,saved,total_interactions) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(uid('metric'),ws.id,p.id,p.publishedMediaId||`demo_${p.id}`,now(),views,reach,likes,comments,shares,saved,total)}const strategy=buildStrategy(ws.id);return sendJson(res,200,{ok:true,strategy,dashboard:analyticsDashboard(ws.id)})}
  if(req.method==='POST'&&pathname==='/api/analytics/refresh'){const refreshed=await refreshAnalytics(ws),strategy=buildStrategy(ws.id);return sendJson(res,200,{refreshed,strategy,dashboard:analyticsDashboard(ws.id)})}
  if(req.method==='POST'&&pathname==='/api/strategy/rebuild')return sendJson(res,200,buildStrategy(ws.id));
  return sendJson(res,404,{error:'Rota não encontrada'});
}catch(e){console.error(e);if(!res.headersSent)return sendJson(res,500,{error:e.message||'Erro interno'});try{res.end()}catch{}}});

server.listen(PORT,'0.0.0.0',()=>{console.log(`ViraClip AI v7 em http://localhost:${PORT}`);console.log(`SQLite: ${DB_PATH}`);console.log(`IA: ${OPENAI_API_KEY?'conectada':'não configurada'}`);console.log(`FFmpeg: ${exists(FFMPEG_BIN)&&exists(FFPROBE_BIN)?'disponível':'indisponível'}`)});
